### PR TITLE
fix golang-http example

### PR DESCRIPTION
**Pull request by electricjesus**
tried to follow the docs, failed at the first command. source path wasn't correct (probably retained from the move from envoyproxy/envoy repo)

also changed go build to directly write to /output. I hope that's okay

### CODE REVIEW

**Comment by electricjesus** [comment]
done - I appreciate your guidance, @phlax

**Comment by phlax** [comment]
this didnt seem to work

```console
rm: cannot remove '/tmp/tmp.vLr414Yhkp/golang-http/lib/simple.so': Permission denied
```

https://github.com/envoyproxy/examples/actions/runs/10589984186/job/29352990807?pr=112#step:11:19

grepping `simple.so`, i dont see anything in our setup that is trying to rm the file so not sure what that error is - its unclear if its a cause or symptom

i also tried running your PR locally (ie running the `verify.sh` script) and that failed with

```console
Wait (10) failed: bash -c responds_with_header 'rsp-header-from-go: bar-test' http://localhost:10710
```

if you can get it working locally we can figure out any other issues if needed

**Comment by phlax** [comment]
i think the `rm` error is here https://github.com/envoyproxy/examples/blob/1255d01460a7e23ec4c609b9b6af340797e50e46/verify_example.sh#L21-L22 and most likely caused by the build container running as root - not sure if the change to use the direct output is relevant

**Comment by electricjesus** [comment]
@phlax sorry for the delay, was on holidays a bit -- I added a cleanup phase so at least the artifacts `./lib` and `simple.so` but I did it through docker-compose just so it's deleted with the same user (root in this case) as it was created.. hopefully this works! works locally

**Comment by phlax** [comment]
hi @electricjesus i think this should not be necessary

not sure exactly what the issue is - but these tests are to test what is written in the docs - so if it is necessary then that should be in the docs - but really, i dont think it is

did you pinpoint what the problem is exactly?

**Comment by electricjesus** [comment]
@phlax yep - the `./verify-example.sh` script as you pointed out has a couple of rimraf steps but unfortunately the invoked docker-compose up adds artifacts that are owned by root. adding the cleanup phase does allow the tmpdirs to be deleted without issue but I only verified that by running it locally

**Comment by phlax** [comment]
> docker-compose up adds artifacts that are owned by root

in that case i think, better to ensure that it doesnt run as root inside the container

**Comment by phlax** [comment]
did you manage to repro the permission problem locally?

ill give the PR another try shortly and see how far i get

**Comment by electricjesus** [comment]
ah ok thanks @phlax -- looks like i could get docker-compose to run in non-root but i think it's best to do it in `./verify-common.sh`. I could try and set up another PR for that? overall would be better I think for all tests to run non-root

**Comment by phlax** [comment]
> ...  looks like i could get docker-compose to run in non-root but i think it's best to do it in ...

i think it needs to go in _this_ tests composition

**Comment by electricjesus** [comment]
@phlax I think i see what you mean.  in this new commit I added `user` to the build compose file, and also set env var `HOME` to `/tmp` to fix go build cache init issues when running in non-root mode. I also exported GID in verify.sh so that the user field also gets the correct group

**Comment by phlax** [comment]
yeah - so was just doing some testing locally

all passes when running the verify.sh script directly - but if i use bazel it fails

i think the problem is not essentially with the test - the problem is that the test produces root-owned artefacts on end users fs

the wasm build has some code for this i think - see `UID`/`BUILD_UID`

the one annoyance with this is that the user has to do `export UID` before running as otherwise `UID` is in the env but not exported to child procs (ie docker) without explicitly exporting it

**Review by phlax — APPROVED** [review]
lgtm, nice, thanks @electricjesus

**Pull request merged**
